export const POWERBUTTON_ACTIVATION_EVENT = 'POWERBUTTON_ACTIVATION_EVENT';
export const OPEN_DOOR = 'OPEN_DOOR';
export const CHANGE_SCORE = 'CHANGE_SCORE';
export const REVEAL_SPOT = 'REVEAL_SPOT';
